### PR TITLE
Button and Command Manager

### LINKED ISSUE #21: Proper command management system
Currently we just have a switch statement that goes through all the slash commands that exist and then executes the right one. We also have to individually add every command to the registration method that we have. This should be made more dynamic, such that we can, for example, we can get all the classes that have a particular annotation/implement an interface, and then get its `ApplicationCommandRequest` and the method to handle that slash command from there

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
Fixes #21 

Separates commands and buttons from `App`.

### CODE REVIEW

**Comment by heftymouse** [comment]
This is a good start but it doesn't really solve the problem since it still requires command data to be hardcoded outside of the command classes themselves. The ideal system is one where you can just add a class to the command/button package and just have it work without having to touch any other files. You'll have to do some conc reflection stuff to do that but it's worth it imo
There's a couple libraries that make it a lot easier too in case you're interested, like [this](https://github.com/ronmamo/reflections)

**Review by heftymouse — CHANGES_REQUESTED** [review]
see comment

**Comment by BoogieMonster1O1** [comment]
> This is a good start but it doesn't really solve the problem since it still requires command data to be hardcoded outside of the command classes themselves. The ideal system is one where you can just add a class to the command/button package and just have it work without having to touch any other files. You'll have to do some conc reflection stuff to do that but it's worth it imo
> There's a couple libraries that make it a lot easier too in case you're interested, like [this](https://github.com/ronmamo/reflections)

Concern

**Review by heftymouse — APPROVED** [review]
looks good for now

**Comment by heftymouse** [comment]
FUCK

**Comment by heftymouse** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by heftymouse** [comment]
ok epic time to :shipit:

**Pull request merged**
